/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Point;
import java.util.HashMap;
import javax.swing.JFrame;
import org.jdesktop.wonderland.client.jme.JmeClientMain;
import org.jdesktop.wonderland.common.cell.CellID;

/**
 *
 * @author paulby
 */
public class LoadingInfo extends javax.swing.JFrame {

    private static LoadingInfo loadingInfo = new LoadingInfo();
    private final HashMap<CellID, String> currentlyLoading = new HashMap();

    /** Creates new form LoadingInfo */
    private LoadingInfo() {
        initComponents();
    }

    private void startedLoadingImpl(CellID cellID, String avatarname) {
        synchronized(currentlyLoading) {
            currentlyLoading.put(cellID, avatarname);
            if (!isVisible()) {
                EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        JFrame mainFrame = JmeClientMain.getFrame().getFrame();
                        Point loc = mainFrame.getLocationOnScreen();
                        Dimension size = mainFrame.getSize();
                        setLocation(loc.x+size.width/2-getWidth()/2, loc.y+size.height/2-getHeight()/2);
                        setAlwaysOnTop(true);
                        setVisible(true);
                    }
                });
            }
        }
    }

    private void finishedLoadingImpl(CellID cellID, String avatarname) {
        synchronized(currentlyLoading) {
            currentlyLoading.remove(cellID);
            if (currentlyLoading.size()==0)
                EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        setVisible(false);
                    }
                });
        }

    }

    public static void startedLoading(CellID cellID, String avatarname) {
        loadingInfo.startedLoadingImpl(cellID, avatarname);
    }

    public static void finishedLoading(CellID cellID, String avatarname) {
        loadingInfo.finishedLoadingImpl(cellID, avatarname);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 4, true));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        jLabel1.setText("Loading Avatars, please wait.....");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(59, 59, 59)
                .add(jLabel1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
