//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.19 at 09:37:59 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://earth.google.com/kml/2.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jdesktop.wonderland.modules.kmzloader.client.kml_21;
