/*
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.audiomanager.client.voicechat;

import java.awt.event.ActionListener;
import javax.swing.event.ChangeListener;
import javax.swing.SpinnerNumberModel;


/**
 *
 * @author nsimpson
 */
public class HoldPanel extends javax.swing.JPanel {

    private SpinnerNumberModel volumeModel;

    public HoldPanel() {
        initComponents();

	Float value = new Float(0);
        Float min = new Float(0);
        Float max = new Float(10);
        Float step = new Float(.05);
        volumeModel = new SpinnerNumberModel(value, min, max, step);
        volumeSpinner.setModel(volumeModel);
    }

    public void addHoldListener(ActionListener listener) {
        takeOffHoldButton.addActionListener(listener);
    }

    public void removeHoldListener(ActionListener listener) {
        takeOffHoldButton.removeActionListener(listener);
    }

    public void addVolumeChangeListener(ChangeListener listener) {
       volumeSpinner.addChangeListener(listener);
    }

    public void removeVolumeChangeListener(ChangeListener listener) {
        volumeSpinner.removeChangeListener(listener);
    }

    public float getHoldVolume() {
	return (Float) volumeModel.getValue();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holdLabel = new javax.swing.JLabel();
        holdingUsersLabel = new javax.swing.JLabel();
        takeOffHoldButton = new javax.swing.JButton();
        volumeSpinner = new javax.swing.JSpinner();

        setName("Form"); // NOI18N

        holdLabel.setFont(holdLabel.getFont().deriveFont(holdLabel.getFont().getStyle() | java.awt.Font.BOLD));
        holdLabel.setText("On hold volume:");
        holdLabel.setName("holdLabel"); // NOI18N

        holdingUsersLabel.setText(" ");
        holdingUsersLabel.setName("holdingUsersLabel"); // NOI18N

        takeOffHoldButton.setText("Take Off Hold");
        takeOffHoldButton.setName("takeOffHoldButton"); // NOI18N

        volumeSpinner.setName("volumeSpinner"); // NOI18N
        volumeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSpinnerStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(holdLabel)
                        .add(18, 18, 18)
                        .add(volumeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(holdingUsersLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, takeOffHoldButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(holdLabel)
                    .add(volumeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(holdingUsersLabel)
                .add(18, 18, 18)
                .add(takeOffHoldButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void volumeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_volumeSpinnerStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel holdLabel;
    private javax.swing.JLabel holdingUsersLabel;
    private javax.swing.JButton takeOffHoldButton;
    private javax.swing.JSpinner volumeSpinner;
    // End of variables declaration//GEN-END:variables
}
