/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AudioProblemJFrame.java
 *
 * Created on Dec 14, 2009, 12:51:17 PM
 */

package org.jdesktop.wonderland.modules.audiomanager.client;

/**
 *
 * @author jp
 */
public class AudioProblemJFrame extends javax.swing.JFrame {

    AudioManagerClient client;

    /** Creates new form AudioProblemJFrame */
    public AudioProblemJFrame() {
        initComponents();
    }

    public AudioProblemJFrame(AudioManagerClient client) {
	this.client = client;
        initComponents();
    }

    public void setText(String problem) {
	String pattern = "Softphone Problem: ";

	int ix = problem.indexOf(pattern);

	if (ix >= 0) {
	    problem = problem.substring(ix + pattern.length());
	}

	String[] tokens = problem.split("[.]");

	audioProblemLabel.setText(tokens[0].trim());

	if (tokens.length == 1) {
	    audioProblemTextArea.setText("No details.");
	} else {
	    String s = "";

	    for (int i = 1; i < tokens.length; i++) {
		s += tokens[i].trim() + "\n";
	    }

	    audioProblemTextArea.setText(s);
	}

	setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        audioProblemLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        audioProblemTextArea = new javax.swing.JTextArea();
        reconfigureButton = new javax.swing.JButton();
        reconnectButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setTitle("Audio Problem");

        audioProblemLabel.setFont(audioProblemLabel.getFont().deriveFont(audioProblemLabel.getFont().getStyle() | java.awt.Font.BOLD));
        audioProblemLabel.setText("Softphone Problem: ");
        audioProblemLabel.setFocusable(false);
        audioProblemLabel.setRequestFocusEnabled(false);

        audioProblemTextArea.setBackground(new java.awt.Color(238, 238, 238));
        audioProblemTextArea.setColumns(1);
        audioProblemTextArea.setEditable(false);
        audioProblemTextArea.setLineWrap(true);
        audioProblemTextArea.setRows(3);
        audioProblemTextArea.setBorder(null);
        audioProblemTextArea.setFocusable(false);
        audioProblemTextArea.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(audioProblemTextArea);

        reconfigureButton.setText("Reconfigure...");
        reconfigureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconfigureButtonActionPerformed(evt);
            }
        });

        reconnectButton.setText("Reconnect");
        reconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconnectButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .add(audioProblemLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(reconfigureButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(reconnectButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(okButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(audioProblemLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(reconnectButton)
                    .add(reconfigureButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reconfigureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconfigureButtonActionPerformed
	client.testAudio();
    }//GEN-LAST:event_reconfigureButtonActionPerformed

    private void reconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconnectButtonActionPerformed
        client.connectSoftphone();
    }//GEN-LAST:event_reconnectButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
	setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudioProblemJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel audioProblemLabel;
    private javax.swing.JTextArea audioProblemTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JButton reconfigureButton;
    private javax.swing.JButton reconnectButton;
    // End of variables declaration//GEN-END:variables

}
