/*
 * HoldHUDPanel.java
 *
 * Created on July 14, 2009, 10:59 AM
 */

package org.jdesktop.wonderland.modules.audiomanager.client;

import org.jdesktop.wonderland.client.comms.WonderlandSession;

import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.NameTagNode;

import org.jdesktop.wonderland.modules.audiomanager.common.messages.VoiceChatInfoRequestMessage;

import org.jdesktop.wonderland.modules.presencemanager.common.PresenceInfo;

import java.util.ArrayList;

/**
 *
 * @author  jp
 */
public class HoldHUDPanel extends javax.swing.JPanel  implements MemberChangeListener {

    private AudioManagerClient client;
    private WonderlandSession session;

    private String group;

    private InCallHUDPanel inCallHUDPanel;

    /** Creates new form HoldHUDPanel */
    public HoldHUDPanel() {
        initComponents();
    }

    public HoldHUDPanel(AudioManagerClient client, WonderlandSession session,
            String group, InCallHUDPanel inCallHUDPanel) {

	this.client = client;
	this.session = session;
	this.group = group;
	this.inCallHUDPanel = inCallHUDPanel;

        initComponents();

	groupLabel.setText(group);

	client.addMemberChangeListener(group, this);

        session.send(client, new VoiceChatInfoRequestMessage(group));
    }

    private ArrayList<PresenceInfo> members = new ArrayList();

    public void setMemberList() {
	String memberText = "";

	for (PresenceInfo member : members) {
	    memberText += NameTagNode.getDisplayName(
                member.usernameAlias, member.isSpeaking, member.isMuted);

	    memberText += " ";
	}

	this.memberText.setText(memberText);
    }

    public void memberChange(PresenceInfo info, boolean added) {
	if (added) {
	    members.add(info);
	} else {
	    members.remove(info);
	}

	setMemberList();
    }

    public void setMemberList(PresenceInfo[] presenceInfo) {
	members.clear();

	for (int i = 0; i < presenceInfo.length; i++) {
	     members.add(presenceInfo[i]);
	}

	setMemberList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holdButton = new javax.swing.JButton();
        volumeSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        memberText = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();

        holdButton.setText("Hold");
        holdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonActionPerformed(evt);
            }
        });

        volumeSlider.setMaximum(10);
        volumeSlider.setMinorTickSpacing(1);
        volumeSlider.setPaintLabels(true);
        volumeSlider.setPaintTicks(true);
        volumeSlider.setSnapToTicks(true);
        volumeSlider.setValue(1);
        volumeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeSliderStateChanged(evt);
            }
        });

        jLabel1.setText("Volume");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(59, 59, 59)
                        .add(groupLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .add(volumeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(memberText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(holdButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(holdButton)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(groupLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(6, 6, 6)
                        .add(volumeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(memberText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void volumeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeSliderStateChanged
    inCallHUDPanel.setHold(true, volumeSlider.getValue());
}//GEN-LAST:event_volumeSliderStateChanged

private void holdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonActionPerformed
    inCallHUDPanel.setHold(false, 0);
}//GEN-LAST:event_holdButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupLabel;
    private javax.swing.JButton holdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel memberText;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables

}
