/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2008, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * $Revision$
 * $Date$
 * $State$
 */

package org.jdesktop.wonderland.client.media.cell;

import javax.swing.JPanel;
import org.jdesktop.wonderland.common.cell.setup.BasicCellSetup;

/**
 * A panel for the basic cell setup information: origin, rotation, scaling.
 * 
 * @author Jordan Slott <jslott@dev.java.net>
 */
public class BasicCellConfigPanel extends javax.swing.JPanel implements CellConfigPanel {

    /** Creates new form BasicCellConfigPanel */
    public BasicCellConfigPanel() {
        initComponents();
    }

    public String getDisplayName() {
        return "Basic";
    }

    public JPanel getConfigJPanel() {
        return basicTabPanel;
    }

    public <T extends BasicCellSetup> void updateGUI(T setup) {
        // Fetch the origin, rotation, and scaling from the setup
        BasicCellSetup.Origin origin = setup.getOrigin();
        BasicCellSetup.Rotation rotation = setup.getRotation();
        BasicCellSetup.Scaling scaling = setup.getScaling();
        
        // Update the origin text fields
        originXTextField.setText("" + origin.x);
        originYTextField.setText("" + origin.y);
        originZTextField.setText("" + origin.z);
        
        // Update the rotation text fields
        rotationXTextField.setText("" + rotation.x);
        rotationYTextField.setText("" + rotation.y);
        rotationZTextField.setText("" + rotation.z);
        rotationAngleTextField.setText("" + rotation.angle);
        
        // Update the scaling text fields
        scalingXTextField.setText("" + scaling.x);
        scalingYTextField.setText("" + scaling.y);
        scalingZTextField.setText("" + scaling.z);
    }

    public <T extends BasicCellSetup> void updateCellSetup(T setup) {
        // Fetch the origin information and set in the setup class
        setup.origin.x = new Double(originXTextField.getText());
        setup.origin.y = new Double(originYTextField.getText());
        setup.origin.z = new Double(originZTextField.getText());
        
        // Fetch the rotation inforamtion and set in the setup class
        setup.rotation.x = new Double(rotationXTextField.getText());
        setup.rotation.y = new Double(rotationYTextField.getText());
        setup.rotation.z = new Double(rotationZTextField.getText());
        setup.rotation.angle = new Double(rotationAngleTextField.getText());
        
        // Fetch the scaling information and set in the setup class
        setup.scaling.x = new Double(scalingXTextField.getText());
        setup.scaling.y = new Double(scalingYTextField.getText());
        setup.scaling.z = new Double(scalingZTextField.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicTabPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        originXTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        originYTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        originZTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rotationXTextField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        rotationYTextField = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        rotationZTextField = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        rotationAngleTextField = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        scalingXTextField = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        scalingYTextField = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        scalingZTextField = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel2.setText("Origin:");

        originXTextField.setColumns(5);
        originXTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        originXTextField.setText("0.0");

        jLabel3.setText("(x:");

        jLabel4.setText(", y:");

        originYTextField.setColumns(5);
        originYTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        originYTextField.setText("0.0");

        jLabel5.setText(", z:");

        originZTextField.setColumns(5);
        originZTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        originZTextField.setText("0.0");

        jLabel6.setText(")");

        jLabel7.setText("Rotation:");

        jLabel8.setText("(x:");

        rotationXTextField.setColumns(5);
        rotationXTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rotationXTextField.setText("0.0");

        jLabel9.setText(", y:");

        rotationYTextField.setColumns(5);
        rotationYTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rotationYTextField.setText("0.0");

        jLabel10.setText(", z:");

        rotationZTextField.setColumns(5);
        rotationZTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rotationZTextField.setText("0.0");

        jLabel11.setText(") @");

        rotationAngleTextField.setColumns(5);
        rotationAngleTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rotationAngleTextField.setText("0.0");

        jLabel12.setText("degrees");

        jLabel13.setText("(x:");

        scalingXTextField.setColumns(5);
        scalingXTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        scalingXTextField.setText("0.0");

        jLabel14.setText(", y:");

        scalingYTextField.setColumns(5);
        scalingYTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        scalingYTextField.setText("0.0");

        jLabel15.setText(", z:");

        scalingZTextField.setColumns(5);
        scalingZTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        scalingZTextField.setText("0.0");

        jLabel16.setText(")");

        jLabel17.setText("Scale:");

        org.jdesktop.layout.GroupLayout basicTabPanelLayout = new org.jdesktop.layout.GroupLayout(basicTabPanel);
        basicTabPanel.setLayout(basicTabPanelLayout);
        basicTabPanelLayout.setHorizontalGroup(
            basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(basicTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel17))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(basicTabPanelLayout.createSequentialGroup()
                        .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(basicTabPanelLayout.createSequentialGroup()
                                .add(jLabel8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rotationXTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rotationYTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(rotationZTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11))
                            .add(basicTabPanelLayout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(originXTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(originYTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(originZTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel6)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rotationAngleTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel12))
                    .add(basicTabPanelLayout.createSequentialGroup()
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scalingXTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scalingYTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(scalingZTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel16)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        basicTabPanelLayout.setVerticalGroup(
            basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(basicTabPanelLayout.createSequentialGroup()
                .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(originXTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jLabel3)
                    .add(originYTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(originZTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(rotationXTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(jLabel8)
                    .add(rotationYTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(rotationZTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(rotationAngleTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(basicTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(scalingXTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(jLabel13)
                    .add(scalingYTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15)
                    .add(scalingZTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 603, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(basicTabPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(0, 5, Short.MAX_VALUE)
                    .add(basicTabPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 5, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basicTabPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField originXTextField;
    private javax.swing.JFormattedTextField originYTextField;
    private javax.swing.JFormattedTextField originZTextField;
    private javax.swing.JFormattedTextField rotationAngleTextField;
    private javax.swing.JFormattedTextField rotationXTextField;
    private javax.swing.JFormattedTextField rotationYTextField;
    private javax.swing.JFormattedTextField rotationZTextField;
    private javax.swing.JFormattedTextField scalingXTextField;
    private javax.swing.JFormattedTextField scalingYTextField;
    private javax.swing.JFormattedTextField scalingZTextField;
    // End of variables declaration//GEN-END:variables
}
