#!/bin/sh
#
if [ -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    #
    # Reset the license checks since these questions have to be answered
    # each time the installation happens.
    #
    db_reset lg3d-wonderland/license-declined
    db_reset lg3d-wonderland/license-check
    db_reset lg3d-wonderland/license-info
fi

if test -x /usr/bin/update-menus; then update-menus; fi

chmod 777 -R /usr/share/lg3d-wonderland/data
touch /usr/share/lg3d-wonderland/ext/darkstar/WonderlandMain.cfg
chmod 777 /usr/share/lg3d-wonderland/ext/darkstar/WonderlandMain.cfg