/*
 * UserListJFrame.java
 *
 * Created on January 22, 2009, 2:52 PM
 */
package org.jdesktop.wonderland.modules.audiomanager.client;

import org.jdesktop.wonderland.modules.audiomanager.common.messages.AudioVolumeMessage;

import org.jdesktop.wonderland.modules.presencemanager.client.PresenceManager;
import org.jdesktop.wonderland.modules.presencemanager.client.PresenceManagerListener;
import org.jdesktop.wonderland.modules.presencemanager.client.PresenceManagerListener.ChangeType;

import org.jdesktop.wonderland.modules.presencemanager.common.PresenceInfo;


import org.jdesktop.wonderland.client.cell.Cell;
import org.jdesktop.wonderland.client.cell.ChannelComponent;

import org.jdesktop.wonderland.client.softphone.SoftphoneControlImpl;


import java.util.Arrays;
import java.util.HashMap;

import java.awt.Point;

import java.util.logging.Logger;

import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.NameTagNode;

/**
 *
 * @author  jp
 */
public class UserListJFrame extends javax.swing.JFrame implements PresenceManagerListener,
        VolumeChangeListener {

    private static final Logger logger =
            Logger.getLogger(UserListJFrame.class.getName());
    private ChannelComponent channelComp;
    private PresenceManager pm;
    private String username;

    /** Creates new form UserListJFrame */
    public UserListJFrame(PresenceManager pm, Cell cell) {
        this.pm = pm;

        initComponents();

        channelComp = cell.getComponent(ChannelComponent.class);

        setTitle("Users");

        pm.addPresenceManagerListener(this);

        PresenceInfo info = pm.getPresenceInfo(cell.getCellID());

        if (info == null) {
            logger.warning("No Presence info for cell " + cell.getCellID());
            return;
        }

        username = info.usernameAlias;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();

        userList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        userList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(userList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private HashMap<String, VolumeControlJFrame> userMap = new HashMap();

    public Object[] getSelectedValues() {
        return userList.getSelectedValues();
    }

private void userListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userListValueChanged
    Object[] selectedValues = userList.getSelectedValues();

    for (int i = 0; i < selectedValues.length; i++) {
        String username = NameTagNode.getUsername((String) selectedValues[i]);

        VolumeControlJFrame volumeControl = userMap.get(username);

        if (volumeControl == null) {
            volumeControl = new VolumeControlJFrame(this, username);
            volumeControl.setLocation(new Point((int) (getLocation().getX() + getWidth()),
                    (int) getLocation().getY()));
            userMap.put(username, volumeControl);

            if (username.equals(this.username)) {
                volumeControl.setTitle("Master Volume");
            } else {
                volumeControl.setTitle("Private Volume for " + username);
            }
        }

        volumeControl.setVisible(true);
    }

    userList.clearSelection();
    }//GEN-LAST:event_userListValueChanged

    public void volumeChanged(String username, double volume) {
        PresenceInfo[] info = pm.getAliasPresenceInfo(username);

        if (info == null) {
            logger.warning("volumeChanged unable to get presence info for " + username);
            return;
        }

        SoftphoneControlImpl sc = SoftphoneControlImpl.getInstance();

        channelComp.send(new AudioVolumeMessage(info[0].cellID, sc.getCallID(), volume));
    }

    public void done() {
        setVisible(false);
    }
    private String[] userData;

    public void setUserList() {
        PresenceInfo[] presenceInfoList = pm.getAllUsers();

        String[] userData = new String[presenceInfoList.length];

        for (int i = 0; i < presenceInfoList.length; i++) {
            PresenceInfo info = presenceInfoList[i];

	    userData[i] = NameTagNode.getDisplayName(info.usernameAlias, info.isSpeaking,
		info.isMuted);

            if (info.callID == null) {
                // It's a virtual player, skip it.
                continue;
            }

            userData[i] = NameTagNode.getDisplayName(info.usernameAlias, info.isSpeaking,
                    info.isMuted);
        }

	SortUsers.sort(userData);
        setUserList(userData);
    }

    public void setUserList(String[] userData) {
        this.userData = userData;

        userList.setListData(userData);
    }

    public void presenceInfoChanged(PresenceInfo info, ChangeType type) {
        setUserList();
    }

    public void aliasChanged(String previousAlias, PresenceInfo info) {
        VolumeControlJFrame volumeControl = userMap.remove(previousAlias);

        if (volumeControl != null) {
            userMap.put(info.usernameAlias, volumeControl);
        }

        setUserList();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList userList;
    // End of variables declaration//GEN-END:variables
}
