package org.jdesktop.wonderland.modules.audiomanager.client;

import org.jdesktop.wonderland.client.comms.WonderlandSession;

import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.NameTagNode;

import org.jdesktop.wonderland.modules.presencemanager.common.PresenceInfo;

import java.util.ArrayList;

import java.util.logging.Logger;

/*
 * HoldDialog.java
 *
 * Created on April 22, 2009, 12:45 PM
 */



/**
 *
 * @author  jp
 */
public class HoldDialog extends javax.swing.JFrame implements MemberChangeListener {

    private static final Logger logger =
        Logger.getLogger(HoldDialog.class.getName());

    private AudioManagerClient client;
    private WonderlandSession session;

    private String group;

    private InCallDialog inCallDialog;

    /** Creates new form HoldDialog */
    public HoldDialog() {
        initComponents();
    }

    public HoldDialog(AudioManagerClient client, WonderlandSession session,
            String group, InCallDialog inCallDialog) {

	this.client = client;
	this.session = session;
	this.group = group;
	this.inCallDialog = inCallDialog;

        initComponents();

	inCallDialog.addMemberChangeListener(this);

	setMembers();
    }

    public void setMembers() {
	PresenceInfo[] members = inCallDialog.getMembers().toArray(new PresenceInfo[0]);

	String memberText = "";

	for (int i = 0; i < members.length; i++) {
	    PresenceInfo member = members[i];

	    memberText += NameTagNode.getDisplayName(
                member.usernameAlias, member.isSpeaking, member.isMuted, member.inSecretChat);

	    memberText += " ";
	}

	userText.setText(memberText);
    }

    public void memberAdded(PresenceInfo info) {
	setMembers();
    }

    public void memberRemoved(PresenceInfo info) {
	setMembers();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setText("On Hold:");

        userText.setEditable(false);
        userText.setText("                                                                   ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(userText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .add(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(userText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    inCallDialog.setVisible(true);
    inCallDialog.setHold(false);
    setVisible(false);
}//GEN-LAST:event_formMouseClicked

private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    inCallDialog.setVisible(true);
    inCallDialog.setHold(false);
    setVisible(false);
}//GEN-LAST:event_formMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoldDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables

}
