/*
 * NamePropertiesJFrame.java
 *
 * Created on May 28, 2009, 4:19 PM
 */

package org.jdesktop.wonderland.modules.audiomanager.client;

import org.jdesktop.wonderland.modules.presencemanager.common.PresenceInfo;

import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.AvatarNameEvent;

import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.NameTagNode;
import org.jdesktop.wonderland.modules.avatarbase.client.jme.cellrenderer.NameTagNode.EventType;

import org.jdesktop.wonderland.client.input.InputManager;

/**
 *
 * @author  jp
 */
public class NamePropertiesJFrame extends javax.swing.JFrame {

    PresenceInfo presenceInfo;

    private enum NameTagAttribute {
	HIDE,
	SMALL_FONT,
	REGULAR_FONT,
	LARGE_FONT
    };

    NameTagAttribute originalMyNameTagAttribute = NameTagAttribute.REGULAR_FONT;
    NameTagAttribute myNameTagAttribute = NameTagAttribute.REGULAR_FONT;

    NameTagAttribute originalOtherNameTagAttributes = NameTagAttribute.REGULAR_FONT;
    NameTagAttribute otherNameTagAttributes = NameTagAttribute.REGULAR_FONT;

    /** Creates new form NamePropertiesJFrame */
    public NamePropertiesJFrame() {
        initComponents();
    }

    public NamePropertiesJFrame(PresenceInfo presenceInfo) {
	this.presenceInfo = presenceInfo;

        initComponents();

	applyButton.setEnabled(false);
	OKButton.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        myNameHideRadioButton = new javax.swing.JRadioButton();
        myNameRegularRadioButton = new javax.swing.JRadioButton();
        myNameLargeRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        otherNamesHideRadioButton = new javax.swing.JRadioButton();
        otherNamesRegularRadioButton = new javax.swing.JRadioButton();
        otherNamesLargeRadioButton = new javax.swing.JRadioButton();
        OKButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        otherNamesSmallRadioButton = new javax.swing.JRadioButton();
        myNameTagSmallRadioButton = new javax.swing.JRadioButton();
        applyButton = new javax.swing.JButton();

        jLabel1.setText("My Name:");

        buttonGroup1.add(myNameHideRadioButton);
        myNameHideRadioButton.setText("Hide");
        myNameHideRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myNameHideRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(myNameRegularRadioButton);
        myNameRegularRadioButton.setSelected(true);
        myNameRegularRadioButton.setText("Regular");
        myNameRegularRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myNameRegularRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(myNameLargeRadioButton);
        myNameLargeRadioButton.setText("Large");
        myNameLargeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myNameLargeRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Other Names:");

        buttonGroup2.add(otherNamesHideRadioButton);
        otherNamesHideRadioButton.setText("Hide");
        otherNamesHideRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNamesHideRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(otherNamesRegularRadioButton);
        otherNamesRegularRadioButton.setSelected(true);
        otherNamesRegularRadioButton.setText("Regular");
        otherNamesRegularRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNamesRegularRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(otherNamesLargeRadioButton);
        otherNamesLargeRadioButton.setText("Large");
        otherNamesLargeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNamesLargeRadioButtonActionPerformed(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(otherNamesSmallRadioButton);
        otherNamesSmallRadioButton.setText("small");
        otherNamesSmallRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNamesSmallRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(myNameTagSmallRadioButton);
        myNameTagSmallRadioButton.setText("small");
        myNameTagSmallRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myNameTagSmallRadioButtonActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(myNameHideRadioButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(myNameTagSmallRadioButton))
                            .add(layout.createSequentialGroup()
                                .add(otherNamesHideRadioButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(otherNamesSmallRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancelButton)
                        .add(55, 55, 55)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(applyButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(OKButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(myNameRegularRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(myNameLargeRadioButton))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(otherNamesRegularRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(otherNamesLargeRadioButton)))
                .add(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(myNameHideRadioButton)
                    .add(myNameTagSmallRadioButton)
                    .add(myNameRegularRadioButton)
                    .add(myNameLargeRadioButton)
                    .add(jLabel1))
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(otherNamesHideRadioButton)
                    .add(otherNamesSmallRadioButton)
                    .add(otherNamesRegularRadioButton)
                    .add(otherNamesLargeRadioButton))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(OKButton)
                    .add(applyButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
    applyChanges();
    setVisible(false);
}//GEN-LAST:event_OKButtonActionPerformed

private void myNameHideRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myNameHideRadioButtonActionPerformed
    myNameTagAttribute = NameTagAttribute.HIDE;

    enableButtons();
}//GEN-LAST:event_myNameHideRadioButtonActionPerformed

private void myNameTagSmallRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myNameTagSmallRadioButtonActionPerformed
    myNameTagAttribute = NameTagAttribute.SMALL_FONT;

    enableButtons();
}//GEN-LAST:event_myNameTagSmallRadioButtonActionPerformed

private void myNameRegularRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myNameRegularRadioButtonActionPerformed
    myNameTagAttribute = NameTagAttribute.REGULAR_FONT;

    enableButtons();
}//GEN-LAST:event_myNameRegularRadioButtonActionPerformed

private void myNameLargeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myNameLargeRadioButtonActionPerformed
    myNameTagAttribute = NameTagAttribute.LARGE_FONT;

    enableButtons();
}//GEN-LAST:event_myNameLargeRadioButtonActionPerformed

private void otherNamesHideRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNamesHideRadioButtonActionPerformed
    otherNameTagAttributes = NameTagAttribute.HIDE;

    enableButtons();
}//GEN-LAST:event_otherNamesHideRadioButtonActionPerformed

private void otherNamesSmallRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNamesSmallRadioButtonActionPerformed
    otherNameTagAttributes = NameTagAttribute.SMALL_FONT;

    enableButtons();
}//GEN-LAST:event_otherNamesSmallRadioButtonActionPerformed

private void otherNamesRegularRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNamesRegularRadioButtonActionPerformed
    otherNameTagAttributes = NameTagAttribute.REGULAR_FONT;

    enableButtons();
}//GEN-LAST:event_otherNamesRegularRadioButtonActionPerformed

private void otherNamesLargeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNamesLargeRadioButtonActionPerformed
    otherNameTagAttributes = NameTagAttribute.LARGE_FONT;

    enableButtons();
}//GEN-LAST:event_otherNamesLargeRadioButtonActionPerformed

private void enableButtons() {
    if (myNameTagAttribute != originalMyNameTagAttribute ||
	otherNameTagAttributes != originalOtherNameTagAttributes) {

	applyButton.setEnabled(true);
	OKButton.setEnabled(true);
    } else {
	applyButton.setEnabled(false);
	OKButton.setEnabled(false);
    }
}

private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
    applyChanges();
}//GEN-LAST:event_applyButtonActionPerformed

private void applyChanges() {
    AvatarNameEvent avatarNameEvent;

    if (myNameTagAttribute != originalMyNameTagAttribute) {
	originalMyNameTagAttribute = myNameTagAttribute;

        switch (myNameTagAttribute) {
        case HIDE:
            avatarNameEvent = new AvatarNameEvent(EventType.HIDE,
                presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);

            InputManager.inputManager().postEvent(avatarNameEvent);
	    break;

        case SMALL_FONT:
            avatarNameEvent = new AvatarNameEvent(EventType.SMALL_FONT,
                presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
            InputManager.inputManager().postEvent(avatarNameEvent);
	    break;

        case REGULAR_FONT:
            avatarNameEvent = new AvatarNameEvent(EventType.REGULAR_FONT,
                presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
            InputManager.inputManager().postEvent(avatarNameEvent);
	    break;

        case LARGE_FONT:
            avatarNameEvent = new AvatarNameEvent(EventType.LARGE_FONT,
                presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
            InputManager.inputManager().postEvent(avatarNameEvent);
	    break;
        }
    }

    if (otherNameTagAttributes == originalOtherNameTagAttributes) {
	enableButtons();
	return;
    }

    originalOtherNameTagAttributes = otherNameTagAttributes;

    enableButtons();

    switch (otherNameTagAttributes) {
    case HIDE:
	NameTagNode.setOtherNameTags(EventType.HIDE, 
            presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
	break;

    case SMALL_FONT:
	NameTagNode.setOtherNameTags(EventType.SMALL_FONT, 
            presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
	break;

    case REGULAR_FONT:
	NameTagNode.setOtherNameTags(EventType.REGULAR_FONT, 
            presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
	break;

    case LARGE_FONT:
	NameTagNode.setOtherNameTags(EventType.LARGE_FONT, 
            presenceInfo.userID.getUsername(), presenceInfo.usernameAlias);
	break;
    }
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NamePropertiesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JButton applyButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton myNameHideRadioButton;
    private javax.swing.JRadioButton myNameLargeRadioButton;
    private javax.swing.JRadioButton myNameRegularRadioButton;
    private javax.swing.JRadioButton myNameTagSmallRadioButton;
    private javax.swing.JRadioButton otherNamesHideRadioButton;
    private javax.swing.JRadioButton otherNamesLargeRadioButton;
    private javax.swing.JRadioButton otherNamesRegularRadioButton;
    private javax.swing.JRadioButton otherNamesSmallRadioButton;
    // End of variables declaration//GEN-END:variables

}
