/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2008, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * $Revision$
 * $Date$
 * $State$
 */
package org.jdesktop.wonderland.client;

import java.util.Iterator;
import org.jdesktop.wonderland.client.comms.LoginParameters;
import org.jdesktop.wonderland.client.comms.WonderlandServerInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.wonderland.client.comms.LoginFailureException;
import sun.misc.Service;

/**
 *
 * @author  paulby
 */
public class Main extends javax.swing.JFrame {
    private static final Logger logger =
            Logger.getLogger(Main.class.getName());
    
    /** the session for communicating with the server */
    private Wonderland3DClientSession session;
    
    /** Creates new form Main */
    private Main() {
        // create UI components
        initComponents();

        WonderlandServerInfo server = new WonderlandServerInfo("localhost", 1139);
        LoginParameters loginParams = new LoginParameters("foo", "test".toCharArray());
        
        // create a session
        session = new Wonderland3DClientSession(server);
                
        // initialize plugins
        loadPlugins();
        
        try {
            session.login(loginParams);
        } catch (LoginFailureException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Load client plugins.  Plugins implement the ClientPlugin interface
     * and register using the Java ServiceLoader mechanism.
     */
    private void loadPlugins() {
        // initialize plugins
        for (Iterator<ClientPlugin> plugins = Service.providers(ClientPlugin.class);
             plugins.hasNext();)
        {
            ClientPlugin plugin = plugins.next();
            
            logger.info("Initializing plugin: " + plugin);
            plugin.initialize();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setText("File");

        exitMI.setText("Exit");
        fileMenu.add(exitMI);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMI;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar mainMenuBar;
    // End of variables declaration//GEN-END:variables
    
}
