#!/bin/sh

# usage: genzip <pkgbase-dir> <archive-name> <license-file> <pkgname>

tmpscr1=script1.$$
tmpscr2=script2.$$

pkgbase=$1
shift
archive=$1
shift
license=$1
shift
pkgname=$1
shift

echo "Zip'ing ${pkgname}.pkg ..."

zip -r $archive-pkg.zip ${pkgname}.pkg

cat ${pkgbase}/unzipsfx $archive-pkg.zip > $archive

echo "Checksumming..."

sum=`/usr/bin/sum $archive`
index=1
for s in $sum
do
    case $index in
    1)  sum1=$s;
	index=2;
	;;
    2)  sum2=$s;
	index=3;
	;;
    esac
done
echo sum = $sum1 $sum2

cat ${pkgbase}/script1.txt $license ${pkgbase}/script2.txt > $tmpscr1

linecount=`/usr/bin/wc -l < $tmpscr1`
linecount=`expr $linecount + 1`
echo linecount = $linecount

echo "Generating .bin script..."

sed -e s/@LINECOUNT@/$linecount/g   \
    -e s/@SUM1@/$sum1/g		    \
    -e s/@SUM2@/$sum2/g		    \
    -e s/@PKGNAME@/$pkgname/g	    < $tmpscr1 > $tmpscr2
cat $tmpscr2 $archive > $archive.bin
chmod +x $archive.bin

echo "Cleaning up..."
rm -f $tmpscr1
rm -f $tmpscr2
rm -f $archive-pkg.zip
rm -f $archive

echo "Done"
